server.port=8083
spring.application.name=innovatech-ms-autenticacion

# Configuración de base de datos (rellenar según ambiente)
spring.datasource.url=jdbc:postgresql://localhost:5432/innovatech_auth_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# Seguridad y JWT - placeholders
security.jwt.secret=innovatech2026_fullstack3_RichardMoreano
security.jwt.expiration=3600000
