spring.application.name=ms-autenticacion
server.port=8082

# Conexión dinámica inyectada desde el orquestador
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# Secreto JWT compartido y centralizado
security.jwt.secret=${JWT_SECRET}